version: '3'
services:
  demo-app-compose:
    image: carolinazzz/docker-demo-app:2.0
    ports:
      - 8000:8000
    environment:
      - MONGO_DB_USERNAME=admin
      - MONGO_DB_PWD=password
  mongodb-compose:
    image: mongo:4.4
    ports:
      - 8001:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongoui-compose:
    image: mongo-express:0.54
    ports:
      - 8002:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-compose
volumes:
  mongo-data:
    driver: local
