version: '3'
services:
  mongodb-compose:
    image: mongo:4.4
    ports:
      - 8001:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongoui-compose:
    image: mongo-express:0.54
    ports:
      - 8002:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-compose
